// Generated by https://quicktype.io

export interface CitiesResponse {
  success: boolean;
  respuesta: City[];
}

export interface City {
  _id: string;
  city: string;
  country: string;
  src: string;
  description: string;
  __v: number;
}
