// Generated by https://quicktype.io

export interface CityResponse {
  success: boolean;
  respuesta: SingleCity;
}

export interface SingleCity {
  _id: string;
  city: string;
  country: string;
  src: string;
  description: string;
  __v: number;
}
